// Generates docker-compose.fleet.yml + monitor/configs/inst-N.json for an
// N-instance fleet (default 10): N test-sites, N monitors (noVNC on
// 6080..608N-1), one dashboard on :7000.
//
//   node gen-fleet.js [count]
//
// Regenerate after changing anything here; the generated files are committed
// so the mini needs no node invocation before `docker compose up`.
//
// .env drives the deployment specifics (see .env.example): MINI_HOST is the
// hostname alerts + dashboard links use for noVNC (the mini's MagicDNS name);
// FLEET_BIND pins published ports to one interface (the mini's Tailscale IP).

const fs = require('fs');
const path = require('path');

const COUNT = parseInt(process.argv[2] || '10', 10);
const cfgDir = path.join(__dirname, 'monitor', 'configs');
fs.mkdirSync(cfgDir, { recursive: true });

const fleet = [];
let yml = `# GENERATED by gen-fleet.js — edit that, not this.
services:
`;

for (let i = 1; i <= COUNT; i++) {
  const label = `inst-${i}`;
  const novncPort = 6080 + (i - 1);

  fs.writeFileSync(path.join(cfgDir, `${label}.json`), JSON.stringify({
    label,
    url: `http://site-${i}:8080`,
    checkIntervalSeconds: 15,
    pixelThreshold: 0.02,
    confirmChecks: 2,
    blockAssets: false,
    country: null,
    progressSelector: '.qbar',
    maskSelectors: ['.qbar'],
  }, null, 2) + '\n');

  // Only the first site/monitor service carries a build: stanza; the rest
  // reference the same image. 10 concurrent duplicate builds of the Chromium
  // image once filled the mini's disk to 100% — never again.
  const siteBuild = i === 1 ? `    build: ./test-site\n` : '';
  const monBuild = i === 1 ? `    build:\n      context: .\n      dockerfile: docker/Dockerfile.monitor\n` : '';
  yml += `  site-${i}:
    image: site-monitor-testsite:local
${siteBuild}    environment:
      QUEUE_SIZE: \${QUEUE_SIZE:-1000}
    restart: unless-stopped

  mon-${i}:
    image: site-monitor-monitor:local
${monBuild}    ports:
      - "\${FLEET_BIND:-127.0.0.1}:${novncPort}:6080"
    environment:
      NTFY_SERVER: \${NTFY_SERVER:-https://ntfy.sh}
      NTFY_TOPIC: \${NTFY_TOPIC:-}
      NTFY_TOKEN: \${NTFY_TOKEN:-}
      VNC_PASSWORD: \${VNC_PASSWORD:?set VNC_PASSWORD in .env}
      LIVE_VIEW_URL: http://\${MINI_HOST:-localhost}:${novncPort}/vnc.html?autoconnect=1&resize=scale&quality=3
      STATUS_PORT: "7100"
    volumes:
      - ./monitor/configs/${label}.json:/app/config.json:ro
      - mon-${i}-data:/app/data
    shm_size: 1gb
    depends_on:
      - site-${i}
    restart: unless-stopped

`;

  fleet.push({
    label,
    watcher: `http://mon-${i}:7100`,
    site: `http://site-${i}:8080`,
    novnc: `http://\${MINI_HOST:-localhost}:${novncPort}/vnc.html`,
  });
}

yml += `  dashboard:
    image: site-monitor-dashboard:local
    build: ./dashboard
    ports:
      # 7300 outside: macOS AirPlay Receiver squats on 7000 (host side).
      - "\${FLEET_BIND:-127.0.0.1}:\${DASHBOARD_PORT:-7300}:7000"
    environment:
      FLEET: '${JSON.stringify(fleet).replace(/'/g, "''")}'
    depends_on:
${fleet.map((_, i) => `      - mon-${i + 1}`).join('\n')}
    restart: unless-stopped

volumes:
${fleet.map((_, i) => `  mon-${i + 1}-data:`).join('\n')}
`;

fs.writeFileSync(path.join(__dirname, 'docker-compose.fleet.yml'), yml);
console.log(`wrote docker-compose.fleet.yml + ${COUNT} configs in monitor/configs/`);
console.log('run with: docker compose -f docker-compose.fleet.yml up --build -d');
